### ISSUE TITLE
[Feature] Iterable schema updates, including `user_device` source updates, updating primary keys on `event` & `event_extension`

### ISSUE THREAD

**Issue by fivetran-avinash** [fivetran/dbt_iterable_source#27]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Iterable's schema was updated in the August update of the package. The most notable schema change was the update of the `user_device_history` table [in the old schema](https://docs.google.com/presentation/d/1uxDsylyzrajYNAz-zJJBat-DxZbLPlueA3KM7mGBrQY/edit#slide=id.g22957ad5d71_1_0) to `user_device` in[ the new schema.](https://docs.google.com/presentation/d/1a3EbweWbiu4xNCaGBQV62FLuva9W7PndDmvyITaxtAw/edit#slide=id.g219e65a8a00_0_0). We will need to update our source to point to `user_ device` rather than `user_device_history`, or otherwise our transformation model `iterable__users` will fail if a customer attempts to leverage the `iterable__using_user_device_history` variable ([see the README](https://github.com/fivetran/dbt_iterable/blob/main/README.md#step-4-enablingdisabling-models)).

Also, `_fivetran_user_id` was brought into both `event` and `event_extension` as a primary key. We will need to adjsut our tests on both equivalent staging models to account for that, and make the necessary changes upstream so there are no fanouts on the `iterable_events` model ([click here for the `dbt_iterable` issue](https://github.com/fivetran/dbt_iterable/issues/38)).

A host of additional columns were also added to sources like `campaign_history`, `event_extension`,  `message_type` and `user_history` in the new schema. It might be worth an exploratory glance to see if any of these fields should be added, although it is a secondary priority. 

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-reneeli** [comment]
Closing this out as it's been addressed in the recent release!
