### ISSUE TITLE
Iterable User History runtime

### ISSUE THREAD

**Issue by justin-fundrise** [fivetran/dbt_iterable_source#34]
Is it possible to make this an incremental model in order to speed up the runtime? It seems like in the source table there are updated at timestamps that can be used to process only new/updated records. 

https://github.com/fivetran/dbt_iterable_source/blob/847b282848a98f7ea8947df4f0aa5639649845dc/models/stg_iterable__user_history.sql#L1

**Comment by fivetran-avinash** [comment]
Hi @justin-fundrise ! Thanks for submitting this issue. It certainly is possible for us to add incremental logic, although we haven't really done so in source data models. 

Before we dig deeper, would it be possible for you to add some more details to your issue? [You can look at the bug template here](https://github.com/fivetran/dbt_iterable_source/issues/new?assignees=&labels=type%3Abug&projects=&template=bug-report.yml&title=%5BBug%5D+%3Ctitle%3E) and fill in the details. This'll make it easier for us to diagnose the urgency of addressing this issue and prioritizing it for future work.

**Comment by fivetran-avinash** [comment]
Also @justin-fundrise, have you tried materializing the staging table in your `dbt_project.yml`? That might significantly reduce the run time of this model.

**Comment by fivetran-avinash** [comment]
Hi @justin-fundrise, just circling back here and seeing if materializing the staging tables as views helped here.
