### ISSUE TITLE
[Bug] Remove Source Freshness tests in `src_iterable.yml`

### ISSUE THREAD

**Issue by justin-fundrise** [fivetran/dbt_iterable_source#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

https://github.com/fivetran/dbt_iterable_source/blob/847b282848a98f7ea8947df4f0aa5639649845dc/models/src_iterable.yml#L11-L13

While implementing the iterable package, I am running into an error on my slim ci dbt job. 

during the execution of `dbt source freshness`
I am encountering the error

```
19:57:17 13 of 13 ERROR freshness of iterable.user_unsubscribed_channel_history ......... [ERROR in 0.23s]
19:57:17  
19:57:17
19:57:17  Finished running 13 sources in 0 hours 0 minutes and 3.66 seconds (3.66s).
19:57:18  
19:57:18
19:57:18    Database Error in source user_unsubscribed_channel_history (models/src_iterable.yml)
  002003 (42S02): SQL compilation error:
  Object 'db_name.SRC_ITERABLE.USER_UNSUBSCRIBED_CHANNEL_HISTORY' does not exist or not authorized.

```

Which is correct because I do not have the table `USER_UNSUBSCRIBED_CHANNEL_HISTORY` 

I would expect source freshness to skip this table if it is not explicitly being used. 

### Relevant error log or model output

```shell
19:57:18    Database Error in source user_unsubscribed_channel_history (models/src_iterable.yml)
  002003 (42S02): SQL compilation error:
  Object 'BLUEPRINTS_PROD.SRC_ITERABLE.USER_UNSUBSCRIBED_CHANNEL_HISTORY' does not exist or not authorized.

```
```


### Expected behavior

I would expect source freshness to skip tables that are not being used. 

### Possible solution

_No response_

### dbt Project configurations

```
  iterable:
    +tags:
      ft_iterable
    +schema: fivetran  # this schema name is prefixed to __iterable__
    intermediate:
      +schema: fivetran  # this schema name is prefixed to __int_iterable__
      +tags:
        ft_iterable
  iterable_source:
    +schema: fivetran  # this schema name is prefixed to __stg_iterable__
    +tags:
      ft_iterable_src

vars:
  iterable_database: blueprints_prod
  iterable_schema: src_iterable
  iterable__using_campaign_label_history: false
  iterable__using_user_unsubscribed_message_type: false

```

### Package versions

```  
- package: fivetran/iterable
    version: 0.12.0
```

### What database are you using dbt with?

snowflake

### How are you running this dbt package?

dbt Cloud™

### dbt Version

versionless

### Additional Context

_No response_

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance.
- [ ] No.

**Comment by fivetran-avinash** [comment]
Hi @justin-fundrise , 

try setting this config in your `dbt_project.yml`. That should exclude a source from freshness calculations.

`freshness: null`

**Comment by justin-fundrise** [comment]
I think it would be okay to remove the freshness checks. This is something that is more specific to a business’s needs depending on their use case of the data.

**Comment by fivetran-avinash** [comment]
Thanks for the input here @justin-fundrise ! I will go ahead and update this ticket to make a note that we should remove these source freshness checks, as they will cause errors for other customers like the ones you experienced.

**Comment by fivetran-reneeli** [comment]
Thanks for opening this @justin-fundrise ! This has been addressed in the latest release. Let us know if you need anything else.
